name: HardcoreSquad
version: '${version}'
main: de.janniskroeger.hardcoreSquad.HardcoreSquad
api-version: '1.21'
authors: [ janniskroeger ]
commands:
  hc:
    description: Hauptbefehl für den Hardcore-Team-Run
    usage: /hc <start|status|reset|hardreset>
permissions:
  hardcoreteam.admin:
    description: Erlaubt Start und Reset des Hardcore-Team-Runs
    default: op
